Re-adds tritonian gills
VestaOfOrion/Vesta.Bay pull request #125
Opened 2020-12-23 03:04 UTC by N8-Toe

Adds back in my previous greatest code contribution. Tested locally and change log included

2020-12-23 20:16 UTC, Looreydev requested changes
Just change the `delete-after` to make changelog generation a bit easier, besides that this looks fine.

2020-12-23 20:16 UTC, Looreydev commented on html/changelogs/N8gills.yml
> +delete-after: False
```suggestion
delete-after: True
```

2020-12-25 06:26 UTC, N8-Toe commented
Request change done, Ready for re-review

also Merry Christmas

2020-12-26 00:40 UTC, Superhats requested changes
Your changelog file is improperly named. Make sure to follow the naming conventions in the readme;
it should be either [YOUR USERNAME]-PR-[YOUR PR NUMBER].yml or [YOUR USERNAME]-[YOUR BRANCH NAME]

2020-12-26 18:56 UTC, N8-Toe commented
Changelog 2, Return of the log

2020-12-26 19:22 UTC, Superhats approved these changes
Godspeed, spaceman

2020-12-26 19:23 UTC, merged