Expands Salvage Gantry Species
VestaOfOrion/Vesta.Bay pull request #158
Opened 2020-12-28 19:32 UTC by BladeburstNINJA

Adds Skrell, Unathi, Yeosa, Shells, Tajarans, and Genemodders to the Salvage Gantry.

2020-12-29 05:09 UTC, Superhats approved these changes
Code's fine. Still needs a changelog.

2020-12-29 09:22 UTC, BurpleBineapple commented
Same issue as before, I still feel that making the Gantry yet another Bearcat instead of a unique human offship isn't the right move. Skrell/Vox have their own species specific offships and I think it would be nice to have one for humans. Shells/Genemodders I suppose are fine since the former is an IPC and the latter is technically a human subtype.

Minor others issues with this is the odd fact of species like Skrell being on board. This is very much a poor scav vessel with no diplomatic power. It seems strange that a Skrell would work here rather than back in its own space.

Tldr; I would prefer if you want to add species to gantry, add Shells and Genemodders but not the other alien species for the sake of by having 1 human only offship

2020-12-30 00:13 UTC, BurpleBineapple requested changes
Going to finalize this with saying that, if you do want to expand the species to Gantry add only Genemodders and Shells to keep this a Human/IPC only ship.

2021-01-03 18:34 UTC, BurpleBineapple commented
Stale

2021-01-04 21:28 UTC, closed without merging