Adds manual shuttle landing
VestaOfOrion/Vesta.Bay pull request #226
Opened 2021-01-03 06:47 UTC by Anton-Kr

You can now manually land shuttles. For now can only do this on planets, but plan to expand it to everything once this passes and gets settled in. Code taken from Nebula. Shouldn't break anything.

2021-01-03 07:24 UTC, Alanii commented
You should make a mp4 of this. I don't really know what this means.

2021-01-03 09:44 UTC, Anton-Kr commented
@Alanii done

https://user-images.githubusercontent.com/6289191/103475784-5576d000-4d7e-11eb-8506-00d6804e9bf3.mp4

2021-01-03 10:02 UTC, Anton-Kr commented
Not that it will be, but please DNM until I fix this requiring master level piloting

2021-01-03 15:33 UTC, BurpleBineapple requested changes

2021-01-03 15:33 UTC, BurpleBineapple commented on code/modules/overmap/ships/computers/shuttle.dm
> +		if(user.skill_check(SKILL_PILOT, SKILL_PROF))
This is what you need to change to allow manual landing for other skills. I would have it at SKILL_ADEPT so it's experienced or master only.

2021-01-03 19:23 UTC, vhbraz commented
![Aroma](https://user-images.githubusercontent.com/54181477/103486888-fa75c500-4ddf-11eb-9763-fc7982340301.gif)

2021-01-03 21:16 UTC, BurpleBineapple commented
After further consideration, this might be something we should take upstream first. It touches a lot of core files and may cause conflicts when updating in the future.

If you don't want to redo this PR for baystation, I can do it for you and credit you for the original port. If baystation decides they don't want to add this, we can always go ahead and merge this then.

2021-01-04 01:32 UTC, Anton-Kr commented
@BurpleBineapple I'm gonna PR this on Bay and see what comes of it. I'd honestly expect their review to take a while, and if we plan on implementing this regardless of if Bay does it, this could probably be merged when the Bay PR is up, unless there are some other reasons not to that are byond me.

2021-01-04 13:45 UTC, BurpleBineapple approved these changes
Since bay didn't seem interested in the idea, approving this here

2021-01-04 13:51 UTC, merged