Craftable ore box
VestaOfOrion/Vesta.Bay pull request #312
Opened 2021-01-15 10:10 UTC by XElectricX

Adds ore boxes to the wooden crafting list. Costs 20 planks. Changelog soon™.

2021-01-15 20:10 UTC, Tennessee116 commented
Add two sheets of metal. 20 2x4s is probably not the sturdiest construction.

2021-01-15 21:05 UTC, XElectricX commented
I do not think that is possible with the crafting mechanics. You can only craft with one material type. Unless that was changed.

2021-01-16 16:06 UTC, BurpleBineapple commented
> I do not think that is possible with the crafting mechanics. You can only craft with one material type. Unless that was changed.

I would say make it a steel frame first, then add 20 planks to the assembly to craft an ore box. It's a small thing but to me this just seems like a way to get around the small space of the Garuda.

2021-01-16 16:07 UTC, BurpleBineapple requested changes
> I do not think that is possible with the crafting mechanics. You can only craft with one material type. Unless that was changed.

I would say make it a steel frame first, then add 20 planks to the assembly to craft an ore box. It's a small thing but to me this just seems like a way to get around the small space of the Garuda.

2021-01-16 22:24 UTC, XElectricX commented
Alrighty. I'll work it on it.

2021-01-23 06:02 UTC, closed without merging