Allows genemodders to become most off-ship roles.
VestaOfOrion/Vesta.Bay pull request #328
Opened 2021-01-23 00:35 UTC by EmberShinori

Adds genemodders to unrestricted_species so that they're allowed to be most off-ship roles. Does not allow them to join the Salvage Gantry since that's not wanted, I believe. Also blacklists genemodders from selecting Ascent since genemodder cosmetics aren't removed upon spawning in as Ascent.

2021-01-23 19:27 UTC, BurpleBineapple requested changes
If you could add Shell IPCs to this list, that would be greatly appreciated as well

2021-01-23 19:27 UTC, BurpleBineapple commented on code/__defines/mobs.dm
> +#define UNRESTRICTED_SPECIES list(SPECIES_HUMAN, SPECIES_DIONA, SPECIES_IPC, SPECIES_UNATHI, SPECIES_SKRELL, SPECIES_TRITONIAN, SPECIES_SPACER, SPECIES_VATGROWN, SPECIES_GRAVWORLDER, SPECIES_BOOSTER,
```suggestion
#define UNRESTRICTED_SPECIES list(SPECIES_HUMAN, SPECIES_DIONA, SPECIES_IPC, SPECIES_UNATHI, SPECIES_SKRELL, SPECIES_TRITONIAN, SPECIES_SPACER, SPECIES_VATGROWN, SPECIES_GRAVWORLDER, SPECIES_BOOSTER, SPECIES_MULE, SPECIES_CUSTOM, SPECIES_SHELL)
```

2021-01-23 19:48 UTC, Yawet330 commented on code/__defines/mobs.dm
> +#define UNRESTRICTED_SPECIES list(SPECIES_HUMAN, SPECIES_DIONA, SPECIES_IPC, SPECIES_UNATHI, SPECIES_SKRELL, SPECIES_TRITONIAN, SPECIES_SPACER, SPECIES_VATGROWN, SPECIES_GRAVWORLDER, SPECIES_BOOSTER,
Also SPECIES_ADHERENT too please.

2021-01-24 18:55 UTC, Looreydev approved these changes
Looks alright from my side, @BurpleBineapple.

2021-01-26 01:16 UTC, BurpleBineapple approved these changes

2021-01-26 01:17 UTC, merged